# -*- coding: utf-8 -*-
"""student-data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UAN9LqzJ_ZfFqwKFSKjP9XAjlV4c7w27
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

df1 = pd.read_csv("food_coded.csv")
df=df1[["cook","cuisine","diet_current_coded","eating_out","exercise","fav_cuisine_coded","fav_food","fruit_day","ideal_diet_coded","income","marital_status","on_off_campus","parents_cook","pay_meal_out","sports"]]
df.dropna(axis=0,inplace=True)
df.to_csv("food_choices.csv")

sns.boxplot(data=df).tick_params(labelsize=8.7)
plt.xticks(rotation=45, ha="right")
plt.show()

k = 3
kmeans = KMeans(n_clusters=k, random_state=0).fit(df)
df['Clusters']= kmeans.labels_

fig, axes = plt.subplots(1, k, sharey=True)
axes[0].set_ylabel('Coded Values', fontsize=20)

for i in range(k):
     plt.sca(axes[i])
     plt.xticks(rotation=45,ha='right')
     sns.boxplot(palette="Set1",data = df[df['Clusters'] == i].drop('Clusters',1), ax=axes[i]).tick_params(labelsize=8.7)
        
plt.show()

wcss = []
for i in range(1, 14):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', random_state = 60)
    res = kmeans.fit(df)
    print(res)
    wcss.append(kmeans.inertia_)
plt.plot(range(1, 14), wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()